// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Elecrow3_5_RGB_TFT

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_sldMainSlider
void ui_sldMainSlider_screen_init(void);
lv_obj_t * ui_sldMainSlider;
lv_obj_t * ui_lblElecrowtitle;
void ui_event_btnMainButton(lv_event_t * e);
lv_obj_t * ui_btnMainButton;
lv_obj_t * ui_lblBtnMain;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
lv_obj_t * ui_lblSlider;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_face[12] = {&ui_img_face1_png, &ui_img_face10_png, &ui_img_face11_png, &ui_img_face12_png, &ui_img_face2_png, &ui_img_face3_png, &ui_img_face4_png, &ui_img_face5_png, &ui_img_face6_png, &ui_img_face7_png, &ui_img_face8_png, &ui_img_face9_png};
const lv_img_dsc_t * ui_imgset_splashbkgnd[1] = {&ui_img_splashbkgnd2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_btnMainButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_label_set_property(ui_lblElecrowtitle, _UI_LABEL_PROPERTY_TEXT, "3.5\" TFT\nEXAMPLE");
    }
    if(event_code == LV_EVENT_RELEASED) {
        _ui_label_set_property(ui_lblElecrowtitle, _UI_LABEL_PROPERTY_TEXT, "ELECROW\nTFT");
    }
}
void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_lblSlider, target, "", "");
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_sldMainSlider_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_sldMainSlider);
}
