// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Elecrow3_5_RGB_TFT

#ifndef _ELECROW3_5_RGB_TFT_UI_H
#define _ELECROW3_5_RGB_TFT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_sldMainSlider
void ui_sldMainSlider_screen_init(void);
extern lv_obj_t * ui_sldMainSlider;
extern lv_obj_t * ui_lblElecrowtitle;
void ui_event_btnMainButton(lv_event_t * e);
extern lv_obj_t * ui_btnMainButton;
extern lv_obj_t * ui_lblBtnMain;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_lblSlider;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_blankpgbkgnd_png);    // assets\BlankPgBkgnd.png
LV_IMG_DECLARE(ui_img_face1_png);    // assets\Face1.png
LV_IMG_DECLARE(ui_img_face10_png);    // assets\Face10.png
LV_IMG_DECLARE(ui_img_face11_png);    // assets\Face11.png
LV_IMG_DECLARE(ui_img_face12_png);    // assets\Face12.png
LV_IMG_DECLARE(ui_img_face2_png);    // assets\Face2.png
LV_IMG_DECLARE(ui_img_face3_png);    // assets\Face3.png
LV_IMG_DECLARE(ui_img_face4_png);    // assets\Face4.png
LV_IMG_DECLARE(ui_img_face5_png);    // assets\Face5.png
LV_IMG_DECLARE(ui_img_face6_png);    // assets\Face6.png
LV_IMG_DECLARE(ui_img_face7_png);    // assets\Face7.png
LV_IMG_DECLARE(ui_img_face8_png);    // assets\Face8.png
LV_IMG_DECLARE(ui_img_face9_png);    // assets\Face9.png
LV_IMG_DECLARE(ui_img_splashbkgnd2_png);    // assets\SplashBkgnd2.png

LV_FONT_DECLARE(ui_font_LCD20at8BPP);
LV_FONT_DECLARE(ui_font_LCD22at8BPP);
LV_FONT_DECLARE(ui_font_LCD24at8BPP);
LV_FONT_DECLARE(ui_font_LCD30at8BPP);
LV_FONT_DECLARE(ui_font_Verdana11);
LV_FONT_DECLARE(ui_font_Verdana12);
LV_FONT_DECLARE(ui_font_Verdana14);
LV_FONT_DECLARE(ui_font_Verdana16);
LV_FONT_DECLARE(ui_font_Verdana18);
LV_FONT_DECLARE(ui_font_Verdana24);
LV_FONT_DECLARE(ui_font_Verdana36);
LV_FONT_DECLARE(ui_font_Verdana48);
LV_FONT_DECLARE(ui_font_Verdana8);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
